version: "3.5"

networks:
  default-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.5.0.0/16

services:
  database:
    image: mysql:5.7
    container_name: mjvlab-mysql
    environment:
      MYSQL_USER: controlab
      MYSQL_PASSWORD: controlab
      MYSQL_ROOT_PASSWORD: controlab
      MYSQL_DATABASE: Controlab
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - default-network
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis
    container_name: mjvlab-redis
    command: redis-server
    ports:
      - "6379:6379"

volumes:
  db_data:
    driver: local
